version: 2.0
jobs:
  build:
    run_test:
      docker:
        - image: circleci/python:3.7.4
      steps: # steps that comprise the `build` job
        - checkout # check out source code to working directory
        - run:
            name: Install Python Packages
            command: |
              echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
              pip install --user -r  requirements.txt
        - run:
            name: Run Tests
            command: |
              pytest --html=test-reports/report.html
        - store_test_results:
            path: test-reports
        - store_artifacts:
            path: test-reports